### ISSUE TITLE
how to render in ASP MVC core 6, Views

### ISSUE THREAD

**Issue by fasteddys** [dschreib42/AsyncStateMachine#3]
Hello can you share a view on how to show the current workflow, is there a json export?

**Comment by dschreib42** [comment]
There is no json export available. You can either implement your own export to your custom format (see MermaidStateGraph.cs) or you export using one of the existing exports to graphviz or mermaid. There are online renderers available for these. See README.md.

**Comment by fasteddys** [comment]
Thanks for the guidance, I looked and tried to serialize the class from here https://github.com/dschreib42/AsyncStateMachine/blob/develop/src/AsyncStateMachine/Graphs/MermaidStateGraph.cs as an expando object

Is there a class type I can get out of this to validate, so I can save it and reload from file or DB?

**Comment by dschreib42** [comment]
To restore the persisted state of the state machine you can call 'InitializeAsync(TState initialState)' of the state machine class. The 'CurrentState' property gives you the state to persist.
The code of persisting and restoring state is not part of this repo.
